language: java

env:
  matrix:
    - CASSANDRA_VERSION=2.2.15
    - CASSANDRA_VERSION=3.0.19
    - CASSANDRA_VERSION=3.11.5

cache:
  directories:
    - $HOME/.m2

sudo: false

services:
  - docker

install: true

script: ./mvnw clean install -Pci,testcontainers-cassandra,java11 -Dmaven.javadoc.skip=true -B
